# Pandas Data Management

In [1]:
import pandas as pd

df = pd.read_csv("../_Data/data_jobs.csv")
df['job_posted_date'] = pd.to_datetime(df['job_posted_date'], errors='coerce')

## Sample

* `sample()`: Random sample of items.

Let's get a random sample of the data. You could get a sample with a fixed row number.

In [5]:
df.sample(5)

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
495161,Software Engineer,Python Engineer,"Warsaw, Poland",via Trabajo.org,Full-time,False,Poland,2023-02-05 11:22:03,True,False,Poland,NaN,NaN,NaN,Kyriba,"['python', 'word', 'git']","{'analyst_tools': ['word'], 'other': ['git'], ..."
159559,Senior Data Scientist,Senior Data Scientist,Anywhere,via hh.ru,Full-time,True,Russia,2023-04-04 08:37:49,False,False,Russia,NaN,NaN,NaN,Positive Technologies,"['python', 'pytorch', 'github', 'git', 'docker']","{'libraries': ['pytorch'], 'other': ['github',..."
31321,Software Engineer,Certification Engineer,"Gothenburg, Sweden",via Trabajo.org,Full-time,False,Sweden,2023-04-23 13:10:10,True,False,Sweden,NaN,NaN,NaN,Integro Consulting AB,NaN,NaN
326450,Senior Data Engineer,Senior Data Engineer,"Paris, France",via Recruit.net,Full-time,False,France,2023-08-06 23:54:53,True,False,France,NaN,NaN,NaN,Dott,"['python', 'sql', 'bigquery', 'airflow', 'spar...","{'cloud': ['bigquery'], 'libraries': ['airflow..."
387490,Data Scientist,Machine Leaning and Data Science Analyst,"Cambridge, MA",via LinkedIn,Full-time,False,"New York, United States",2023-07-14 18:03:22,False,False,United States,NaN,NaN,NaN,Link Ventures,['sql'],{'programming': ['sql']}

In [8]:
df.sample(5, random_state=42)

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
502901,Senior Data Engineer,Senior Data Engineer,"St Paul, MN",via BeBee,Full-time,False,"Florida, United States",2023-12-17 11:09:06,False,False,United States,NaN,NaN,NaN,ManpowerGroup,"['sql', 'azure', 'git']","{'cloud': ['azure'], 'other': ['git'], 'progra..."
406337,Senior Data Scientist,Senior Analytics Engineer,"London, UK",via LinkedIn,Full-time,False,United Kingdom,2023-10-06 16:09:56,False,False,United Kingdom,NaN,NaN,NaN,Harnham,"['sql', 'python', 'bigquery', 'snowflake', 'lo...","{'analyst_tools': ['looker'], 'cloud': ['bigqu..."
659951,Data Engineer,Data Engineer,"Newcastle upon Tyne, UK",via Indeed,Full-time,False,United Kingdom,2023-09-06 10:11:25,True,False,United Kingdom,NaN,NaN,NaN,Morgan King,NaN,NaN
541593,Data Analyst,Data Analyst,Malta,via Trabajo.org,Full-time,False,Malta,2023-02-14 21:14:18,True,False,Malta,NaN,NaN,NaN,Konnekt,['jira'],{'async': ['jira']}
425158,Senior Data Engineer,Senior Data Engineer. Job in Amsterdam NBC4i Jobs,"Amsterdam, Netherlands",via NBC4i Jobs,Full-time,False,Netherlands,2023-06-19 16:34:30,True,False,Netherlands,NaN,NaN,NaN,Independent Recruiters,['python'],{'programming': ['python']}

Or you can randomly select a fraction of the data (e.g., 10% of the rows), with or without replacement.

In [10]:
df.sample(frac=0.1, replace=False)

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
318673,Data Engineer,Data Engineer,"Piaseczno, Poland",via Adzuna,Full-time,False,Poland,2023-09-05 17:22:40,False,False,Poland,NaN,NaN,NaN,Bayer Sp. z o.o.,"['python', 'aws', 'graphql', 'terraform']","{'cloud': ['aws'], 'libraries': ['graphql'], '..."
412931,Data Engineer,Data Engineer,Anywhere,via LinkedIn,Full-time,True,"Illinois, United States",2023-09-01 16:29:36,True,False,United States,year,115000.0,NaN,CRG,"['sql', 'sql server', 'azure', 'aws', 'databri...","{'analyst_tools': ['ssis', 'tableau', 'power b..."
210073,Senior Data Engineer,Senior Data Engineer MLOps,Dubai - United Arab Emirates,via Indeed,Full-time,False,United Arab Emirates,2023-01-05 22:49:37,False,False,United Arab Emirates,NaN,NaN,NaN,XA Group,"['python', 'c', 'c++', 'azure', 'tensorflow', ...","{'cloud': ['azure'], 'libraries': ['tensorflow..."
408854,Data Analyst,Staff Business Data Analyst (Anaplan Model Bui...,"Plano, TX",via LinkedIn,Full-time,False,"Texas, United States",2023-04-12 16:01:17,False,False,United States,NaN,NaN,NaN,Intuit,"['excel', 'flow']","{'analyst_tools': ['excel'], 'other': ['flow']}"
635319,Business Analyst,Sr. Financial Analyst,"Vélizy-Villacoublay, France",via BeBee,Full-time,False,France,2023-12-13 12:19:12,False,False,France,NaN,NaN,NaN,Dassault Systèmes,"['sql', 'excel']","{'analyst_tools': ['excel'], 'programming': ['..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298146,Data Engineer,Image and Data Analysis Engineer Intern,"Santa Clara, CA",via Nexxt,Internship,False,"California, United States",2023-02-24 17:01:05,False,False,United States,NaN,NaN,NaN,Applied Materials,['python'],{'programming': ['python']}
89327,Data Scientist,Data Scientist - Consultant,"Bailey's Crossroads, VA",via CareerBuilder,Full-time,False,"New York, United States",2023-02-22 00:23:56,False,True,United States,NaN,NaN,NaN,Guidehouse,"['python', 'r', 'sql']","{'programming': ['python', 'r', 'sql']}"
93451,Data Engineer,Sr. Data Engineer,"KENNEDY SPACE CENTER, FL",via CareerBuilder,Full-time,False,"Texas, United States",2023-05-27 00:08:19,False,False,United States,NaN,NaN,NaN,"Latitude, Inc.","['python', 'sql', 'r', 'snowflake', 'tableau',...","{'analyst_tools': ['tableau'], 'cloud': ['snow..."
694622,Senior Data Engineer,👨💻 Senior/Lead Python Data Engineer,Anywhere,via LinkedIn,Full-time,True,Poland,2023-05-27 10:15:43,False,False,Poland,NaN,NaN,NaN,juucy,"['python', 'sql', 'kafka', 'airflow']","{'libraries': ['kafka', 'airflow'], 'programmi..."
229382,Data Analyst,Data analyst junior H/F,"Paris, France",via Indeed,NaN,False,France,2023-08-07 08:17:20,False,False,France,NaN,NaN,NaN,SIACI SAINT HONORE,"['python', 'pandas', 'numpy', 'scikit-learn']","{'libraries': ['pandas', 'numpy', 'scikit-lear..."